#PAGES
PAGE: 
  HOME:
    - modules/currentWeather.html
    - modules/color.html 
    - modules/alarm.html
  FORECAST:
    - modules/forecast.html
  ALARM:
    - modules/alarm.html
  



#WIFI
SSID: SSID
WPA_KEY:  WIFI_PASSWORD

#MQTT
MQTT_BROKER: BROKER_IP
MQTT_USER: BROKER_USERNAME
MQTT_PASS: BROKER_PASSWORD
MQTT_PORT: BROKER_PORT