#PAGES
PAGE: 
  HOME:
    - currentWeather.html
    - color.html 
    - alarm.html
  FORECAST:
    - forecast.html
  ALARM:
    - alarm.html
  



#WIFI
SSID: SSID
WPA_KEY:  WIFI_PASSWORD

#MQTT
MQTT_BROKER: BROKER_IP
MQTT_USER: BROKER_USERNAME
MQTT_PASS: BROKER_PASSWORD
MQTT_PORT: BROKER_PORT